### ISSUE TITLE
Testing: Integration tests are broken

### ISSUE THREAD

**Issue by csadorf** [Exabyte-io/exaparser#20]
The integration tests fail with the following traceback:

```
$ /bin/bash run-tests.sh 

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
test_espresso_001_shell_job (test_job.TestJobParser) ... FAIL
test_vasp_001_shell_job (test_job.TestJobParser) ... FAIL

======================================================================
FAIL: test_espresso_001_shell_job (test_job.TestJobParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sadorf/local/exabyte/exaparser/tests/integration/test_job.py", line 27, in test_espresso_001_shell_job
    self.assertDeepAlmostEqual(config, read_json(os.path.join(FIXTURES_DIR, "espresso", "shell-job.json")))
  File "tests/__init__.py", line 50, in assertDeepAlmostEqual
    raise exc
AssertionError: Items in the first set but not the second:
'isMultiMaterial'
TRACE: ROOT -> 'workflow'

======================================================================
FAIL: test_vasp_001_shell_job (test_job.TestJobParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sadorf/local/exabyte/exaparser/tests/integration/test_job.py", line 35, in test_vasp_001_shell_job
    self.assertDeepAlmostEqual(config, read_json(os.path.join(FIXTURES_DIR, "vasp", "shell-job.json")))
  File "tests/__init__.py", line 50, in assertDeepAlmostEqual
    raise exc
AssertionError: Items in the first set but not the second:
'isMultiMaterial'
TRACE: ROOT -> 'workflow'

----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (failures=2)
```

The issue appears to be related to commit 9a21bc36 which introduced the `isMultimaterial` key to the job workflow file, however the related fixture has not been updated.

**Comment by csadorf** [comment]
The patches below will make tests pass, but the root cause for this issue should probably be investigated before applying them.

Apply to `tests/fixtures/espresso/shell-job.json`:
```diff
@@ -15,6 +15,7 @@
     "status": "finished",
     "workDir": "",
     "workflow": {
+        "isMultiMaterial": true,
         "name": "Shell Workflow",
         "properties": [],
         "subworkflows": [
@@ -63,50 +64,7 @@
                         "next": "",
                         "postProcessors": [],
                         "preProcessors": [],
-                        "results": [
-                            {
-                                "name": "final_structure"
-                            },
-                            {
-                                "name": "phonon_dos"
-                            },
-                            {
-                                "name": "pressure"
-                            },
-                            {
-                                "name": "atomic_forces"
-                            },
-                            {
-                                "name": "stress_tensor"
-                            },
-                            {
-                                "name": "phonon_dispersions"
-                            },
-                            {
-                                "name": "fermi_energy"
-                            },
-                            {
-                                "name": "density_of_states"
-                            },
-                            {
-                                "name": "zero_point_energy"
-                            },
-                            {
-                                "name": "total_energy_contributions"
-                            },
-                            {
-                                "name": "total_force"
-                            },
-                            {
-                                "name": "band_structure"
-                            },
-                            {
-                                "name": "band_gaps"
-                            },
-                            {
-                                "name": "total_energy"
-                            }
-                        ],
+                        "results": [],
                         "status": "finished",
                         "statusTrack": [
                             {
```
Apply to `tests/fixtures/vasp/shell-job.json`:
```diff
@@ -15,6 +15,7 @@
     "status": "finished",
     "workDir": "",
     "workflow": {
+        "isMultiMaterial": true,
         "name": "Shell Workflow",
         "properties": [],
         "subworkflows": [
@@ -63,50 +64,7 @@
                         "next": "",
                         "postProcessors": [],
                         "preProcessors": [],
-                        "results": [
-                            {
-                                "name": "final_structure"
-                            },
-                            {
-                                "name": "phonon_dos"
-                            },
-                            {
-                                "name": "pressure"
-                            },
-                            {
-                                "name": "atomic_forces"
-                            },
-                            {
-                                "name": "stress_tensor"
-                            },
-                            {
-                                "name": "phonon_dispersions"
-                            },
-                            {
-                                "name": "\nfermi_energy"
-                            },
-                            {
-                                "name": "density_of_states"
-                            },
-                            {
-                                "name": "zero_point_energy"
-                            },
-                            {
-                                "name": "total_energy_contributions"
-                            },
-                            {
-                                "name": "\ntotal_force"
-                            },
-                            {
-                                "name": "band_structure"
-                            },
-                            {
-                                "name": "band_gaps"
-                            },
-                            {
-                                "name": "total_energy"
-                            }
-                        ],
+                        "results": [],
                         "status": "finished",
                         "statusTrack": [
                             {
```
